### ISSUE TITLE
Could you be so kind to add license information

### ISSUE THREAD

**Issue by ivankarpey** [szmulder/PaymentExpress.NetSdk#1]
Hello. I'm considering to use this tiny lib in my project, since we need integration with pxpay 2.0
You will be superkind if you find a time to add license information (MIT license will be superb) to let other's know dose they able to use this lib. Thanks.

**Comment by szmulder** [comment]
Done, And I do upload to NuGet so you can use it easily
https://www.nuget.org/packages/PaymentExpress.NetSdk/

**Comment by ivankarpey** [comment]
Thanks a lot!
